name: analytics
version: "1.0.0"
config-version: 2

profile: dbt_training # needs to align with profiles

# default project folders setting can be modified
model-paths:    ["models"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

# where dbt should put compiled SQL and run results
target-path:  "target"

# folders to clean when running `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# global variables, e.g. thresholds to limit data load during development
# vars:
#   dev_load_threshold_ingest_time: '2026-01-01''

# seeds:
#   +quote_columns: false  # Prevents issues with upper/lower case sensitivity in Snowflake
#   hs_tickets:
#     +database: dbt_training   
#     +schema: hubspot_data
#     +tags: ['hubspot', 'seeds', 'dev']

# our sql models will be organized in subfolders by layer, and we'll use config blocks to set materialization and other configs at the folder level
models:
  dbt_training:
    2_staging:
      +materialized: view

    3_silver:
      +materialized: table
      +database: <database>   # hardcoded to training DB — Module 08 covers generate_database_name
      +schema: dbt_silver_<yourname>  # silver schema

    4_gold:
      +materialized: table
      +database: <database>   # hardcoded to training DB — Module 08 covers generate_database_name
      +schema: dbt_gold_<yourname>  # gold schema


