name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'dbt_training' # MUST match the profile name n profiles.yml

# default paths, can be changed or added to as needed
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

# default target path for compiled SQL and run results; can be changed but not required
target-path: "target"

# directories to be removed by dbt clean; can be changed or added to as needed
clean-targets: ["target", "dbt_packages"]

# model configurations can be set here to apply to all models in subfolders, or models can be configured individually by adding config blocks to the relevant .sql files.
models:
  # persist_docs enables dbt to store descriptions in Snowflake  making it accessible for tools that can read database metadata. 
  +persist_docs:
      relation: true
      column: true
  dbt_training:
    1_staging:
      +materialized: view
    2_silver:
      +materialized: table

# Variables for jinja can be defined heare and referenced in models, seeds, etc. with {{ var('variable_name') }}. They can also be overridden at runtime with --vars or in the dbt Cloud UI.
seeds:
  dbt_training:
    raw_contacts:
      +schema: hubspot_raw
      +alias: contacts
      +column_types:
        id: integer
        pipeline_stage_id: integer
        _loaded_at: timestamp
    raw_pipeline_stages:
      +schema: hubspot_raw
      +alias: pipeline_stages
      +column_types:
        stage_id: integer
        pipeline_id: integer
        sort_order: integer
        probability: double
        is_closed: boolean
        _loaded_at: timestamp
    raw_deals:
      +schema: hubspot_raw
      +alias: deals
      +column_types:
        deal_id: integer
        contact_id: integer
        stage_id: integer
        amount: double
        _loaded_at: timestamp
    raw_products:
      +schema: hubspot_raw
      +alias: products
      +column_types:
        product_id: integer
        price: double
        _loaded_at: timestamp
    raw_prescriptions:
      +schema: hubspot_raw
      +alias: prescriptions
      +column_types:
        prescription_id: integer
        contact_id: integer
        owner_id: integer
        product_id: integer
        quantity: integer
        prescription_date: date
        medication_type: varchar
        dosage_amount: double
        notes: varchar
        created_at: timestamp
        _loaded_at: timestamp
    raw_owners:
      +schema: hubspot_raw
      +alias: owners
      +column_types:
        owner_id: integer
        _loaded_at: timestamp

